// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/lantonster/liberate/internal/config"
	"github.com/lantonster/liberate/internal/server"
)

// Injectors from wire.go:

func InitializeServer() *server.Server {
	configConfig := config.LoadConfig()
	serverServer := server.NewServer(configConfig)
	return serverServer
}
